In [1]:
l=[1,2,2]

In [2]:
type(l)

list

In [3]:
import numpy as np

In [4]:
arr=np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr.dtype


dtype('int32')

array([[[1, 2],
        [2, 0]]])

In [18]:
name=[['ma',111],['la',2222]]

In [19]:
a=np.array(name)

In [20]:
a.dtype

dtype('<U4')

In [21]:
a.shape

(2, 2)

In [15]:
arr

array([[[1, 2],
        [2, 0]]])

In [22]:
a

array([['ma', '111'],
       ['la', '2222']], dtype='<U4')

In [23]:
a[:,1]

array(['111', '2222'], dtype='<U4')

In [31]:
l1=[1,2,2,3,4,4,5,6,6]

In [32]:
a2=np.array(l1)

In [33]:
a2.shape

(9,)

In [34]:
a2

array([1, 2, 2, 3, 4, 4, 5, 6, 6])

In [39]:
x2=a2.reshape(3,3)

In [40]:
x2.shape

(3, 3)

In [42]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a3=[1,2,4,5]

In [46]:
a4+10

array([11, 12, 14, 15])