In [1]:
import cv2

In [2]:
photo=cv2.imread('Desert.jpg')

In [4]:
newphoto=photo[10:100,300:400]
cv2.cvtColor(newphoto,cv2.COLOR_BGR2GRAY)
cv2.imshow('myaward',newphoto)
cv2.waitKey(5000)
cv2.destroyAllWindows()

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [11]:
photo.shape


(768, 1024, 3)

In [16]:
type(photo)

numpy.ndarray

In [19]:
newphoto=cv2.cvtColor(photo,cv2.COLOR_BGR2GRAY)

In [22]:
newphoto.shape

(768, 1024)

In [26]:
newphoto.dtype

dtype('uint8')

NameError: name 'cli' is not defined

In [53]:
newphoto=photo[10:100,300:400]

In [61]:
import numpy as np
b=np.array([30,30])

In [59]:
a6=np.zeros((3,3))

In [60]:
a6+255

array([[255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.]])

In [62]:
a6[1,1:3]=b

In [63]:
a6

array([[ 0.,  0.,  0.],
       [ 0., 30., 30.],
       [ 0.,  0.,  0.]])

In [64]:
x=10

In [65]:
y=20

In [66]:
y=x

In [67]:
y

10

In [68]:
x

10

In [81]:
x=np.zeros((5,4))+234

In [83]:
x.shape

(5, 4)

In [85]:
x.reshape(5,4)

array([[234., 234., 234., 234.],
       [234., 234., 234., 234.],
       [234., 234., 234., 234.],
       [234., 234., 234., 234.],
       [234., 234., 234., 234.]])

In [91]:
!pip install opencv-python