In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [5]:
a=np.array(l)

In [6]:
a

array([1, 2, 3, 4])

In [7]:
l2=[[111,3333],[2222,3333]]

In [8]:
a2=np.array(l2)

In [9]:
a2

array([[ 111, 3333],
       [2222, 3333]])

In [12]:
a2[:,:]

array([[ 111, 3333],
       [2222, 3333]])

In [2]:
import cv2

In [3]:
photo=cv2.imread('Desert.jpg')

In [4]:
photo.shape

(768, 1024, 3)

In [5]:
photo[10:100]=[0,255,0]

In [6]:
cv2.imshow('hi',photo)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [22]:
# remove red color
photo[:,:,2]=0

In [23]:
# 1. remove blue and green color
photo[:,:,0:2]=0

In [27]:
#increase the intensity of blue color
photo[:,:,0]+=100

In [30]:
photo

array([[[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       ...,

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]]

In [31]:
l2

[[111, 3333], [2222, 3333]]

In [32]:
a2

array([[ 111, 3333],
       [2222, 3333]])

In [33]:
a2+10

array([[ 121, 3343],
       [2232, 3343]])

In [63]:
B,G,R=cv2.split(photo)

In [75]:
cv2.merge([Z,G,R])

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [64]:
# 3. remove blue color
B=np.zeros((768,1024))

In [65]:
B.shape

(768, 1024)

In [66]:
B

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
B

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
# 2. remobve blue green
B[:,:]=0

In [53]:
B

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [68]:
B.dtype

dtype('float64')

In [69]:
G.dtype

dtype('uint8')

In [70]:
R.dtype

dtype('uint8')

In [71]:
photo.dtype

dtype('uint8')

In [74]:
Z=B.astype('uint8')